name: Bump Version (release)

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install bump-my-version==1.2.4

      - name: Bump version (patch)
        if: contains(github.event.head_commit.message, '#patch')
        run: bump-my-version bump patch --no-commit --no-tag

      - name: Bump version (minor)
        if: contains(github.event.head_commit.message, '#minor')
        run: bump-my-version bump minor --no-commit --no-tag

      - name: Bump version (major)
        if: contains(github.event.head_commit.message, '#major')
        run: bump-my-version bump major --no-commit --no-tag

      - name: Get new version
        id: get_version
        run: echo "version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Bump version number on release"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
          tag_name: "v${{ steps.get_version.outputs.version }}"
          tagging_message: "Release v${{ steps.get_version.outputs.version }}"
          push_options: "--follow-tags"

      - name: Create Pull Request to merge back release into dev
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Merge release branch back into dev"
          body: "Changes made to the release branch (if any), plus the version bump."
          assignees: "jgostick"
          labels: "high priority"
