name: TestPyPI Release

on:
  push:
    branches: [ c_functions ]
  pull_request:
    branches: [ c_functions ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        # python-version: ['3.10', '3.11', '3.12']
        # os: [windows, macos-13-intel, macos-14-arm]
        # os: [linux-intel, linux-arm, windows, macos-13-intel, macos-14-arm]
        os: [windows,macos-13-intel, macos-14-arm]
        include:
          - archs: auto
            platform: auto
          # - os: linux-intel
          #   runs-on: ubuntu-latest
          # - os: linux-arm
          #   runs-on: ubuntu-24.04-arm
          - os: windows
            runs-on: windows-latest
          - os: macos-13-intel
            # macos-13 was the last x86_64 runner
            runs-on: macos-13
            macOS-version: 13.0
          # - os: macos-13-arm
          #   #  ARM64 for macos-13
          #   runs-on: macos-13-xlarge
          #   macOS-version: 13.0
          - os: macos-14-arm
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest
            macOS-version: 14.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install PoreSpy and Python dependencies
        run: |
          uv pip install -r pyproject.toml --system
          uv pip install --system -e .[build]
          pip install meson
          pip install cibuildwheel
          pip install build

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      # - name: Bump up version and create tag
      #   run: |
      #     hatch version ${{ github.event.inputs.version }}
      #     echo "VERSION=v$(hatch version)" >> $GITHUB_ENV

      # - name: Commit version bump + push tag
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Bump version to ${{ env.VERSION }}
      #     commit_author: GitHub Actions <actions@github.com>
      #     tagging_message: ${{ env.VERSION }}

      - name: Install Ninja on Windows
        if: runner.os == 'Windows'
        run: choco install ninja -y

      # - name: Clean up any existing build artifacts
      #   shell: bash
      #   run: |
      #     rm -f src/porespy/beta/*.so
      #     rm -f src/porespy/beta/*.dylib
      #     rm -f src/porespy/beta/*.dll
      #     rm -rf src/porespy_c/build

      - name: Set up build directory and compile
        run: |
          cd src/porespy_c
          meson setup build --buildtype=plain --vsenv
          meson compile -C build

      - name: Move shared library into Python package
        shell: bash
        run: |
          cd src/porespy_c
          if [ "$RUNNER_OS" == "Linux" ]; then
            mv build/libwalker.so ../porespy/beta/
          elif [ "$RUNNER_OS" == "macOS" ]; then
            mv build/libwalker.dylib ../porespy/beta/
          elif [ "$RUNNER_OS" == "Windows" ]; then
            mv build/walker.dll ../porespy/beta/
          fi

      # - name: ls
      #   shell: bash
      #   run: ls -lR src/porespy/beta

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_PLATFORM: ${{ matrix.platform }}
          CIBW_ARCHS: ${{ matrix.archs }}
          # CIBW_ARCHS_LINUX: auto64
          CIBW_SKIP: '*-musllinux_* pp*'
          CIBW_BUILD: cp310* cp311* cp312*
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macOS-version }}
          CIBW_BUILD_VERBOSITY: 1
          # CIBW_BEFORE_BUILD: "rm -f src/porespy/beta/*.so src/porespy/beta/*.dylib src/porespy/beta/*.dll"
          # macOS specific configurations
          # CIBW_ARCHS_MACOS: "arm64 x86_64"
          # CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=${{ matrix.macOS-version }}"
          # Linux specific configurations
          # CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair --plat manylinux2014_x86_64 -w {dest_dir} {wheel}"
          # macOS specific configurations
          # CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel --require-archs arm64 --require-archs x86_64 -w {dest_dir} {wheel}"

      # - name: ls
      #   shell: bash
      #   run: ls -lR wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    # if: startsWith(github.event.head_commit.message, '[Release:]')
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true
    
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}
          verbose: true
